// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDczaOP5A7F17outFs1584hff4c8to5Dy4',
    appId: '1:1026109213891:web:9fdfbf4fc19041ae2be676',
    messagingSenderId: '1026109213891',
    projectId: 'todo-clean-1234567',
    authDomain: 'todo-clean-1234567.firebaseapp.com',
    storageBucket: 'todo-clean-1234567.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJc2Xa_14aV6eUCMIIcChOmujX4Epkg-4',
    appId: '1:1026109213891:android:8f2069808b2787e62be676',
    messagingSenderId: '1026109213891',
    projectId: 'todo-clean-1234567',
    storageBucket: 'todo-clean-1234567.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoQ3cJt7fwuxRlye4M8NNx2kUYxZo08-8',
    appId: '1:1026109213891:ios:da7fcf4c52be5a382be676',
    messagingSenderId: '1026109213891',
    projectId: 'todo-clean-1234567',
    storageBucket: 'todo-clean-1234567.appspot.com',
    iosBundleId: 'com.example.cleanGetxCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoQ3cJt7fwuxRlye4M8NNx2kUYxZo08-8',
    appId: '1:1026109213891:ios:8d08c54aaf96df4e2be676',
    messagingSenderId: '1026109213891',
    projectId: 'todo-clean-1234567',
    storageBucket: 'todo-clean-1234567.appspot.com',
    iosBundleId: 'com.example.cleanGetxCourse.RunnerTests',
  );
}
